before_script:
  - sudo python3 -mvenv /usr/local/libexec/poetry
  - sudo /usr/local/libexec/poetry/bin/python -mpip install -q poetry
  - sudo ln -s /usr/local/libexec/poetry/bin/poetry /usr/local/bin

test with pip.conf alone:
  script:
    - poetry install -vvv
    - poetry run pytest

test with environment:
  variables:
    PIP_REGISTRY_URL: $MY_PIP_REGISTRY_URL
  script:
    - poetry install -vvv
    - poetry run pytest 